# Python Data Preparation Lab — Classroom Hybrid
## Module 2, Class 2 — NumPy & Pandas

This version keeps the **original lab backbone** and adds an **in-class sync flow** for your lesson.

### In class we focus on:
1. NumPy intuition
2. Loading a dataset
3. Inspecting structure
4. Selecting columns
5. Filtering rows
6. Grouping and summarizing

### For homework / full lab we continue with:
1. Missing values
2. Duplicates
3. Date conversion
4. Derived customer features
5. Saving cleaned outputs

> Goal: keep the **original lab strength**, but make the notebook easier to teach live with Darya's slides.

## Start here
- Open this notebook in Colab
- For the live lesson, use `sample_superstore_lesson.csv`
- For stronger homework practice later, use the full `SampleSuperstore.csv` from Kaggle
- Run cells from top to bottom
- If something breaks, do **not** panic — read the error and ask for help

In [1]:
import pandas as pd
import numpy as np

## Step 0 — Load the dataset

**Option A (classroom):** use `sample_superstore_lesson.csv` for the lesson.

**Option B (full homework):** upload `SampleSuperstore.csv` from Kaggle.

**Option C:** use your own path or mounted drive.

In [5]:
# Option A: Upload in Colab
# from google.colab import files
# uploaded = files.upload()
# df = pd.read_csv('sample_superstore_lesson.csv')

# Option B: Full dataset from Kaggle
df = pd.read_csv('train.csv', index_col = 0)

# # Option C: Auto-try common filenames
# try:
#     df = pd.read_csv('sample_superstore_lesson.csv')
#     print('Loaded classroom lesson dataset: sample_superstore_lesson.csv')
# except FileNotFoundError:
#     df = pd.read_csv('SampleSuperstore.csv')
#     print('Loaded full dataset: SampleSuperstore.csv')

# print(df.head(3))

df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

---
# IN CLASS — Part 1: NumPy intuition

NumPy is useful for **fast operations on arrays**.

In [6]:
arr = np.array([10, 20, 30, 40])

print("Array:", arr)
print("Type:", type(arr))
print("Shape:", arr.shape)
print("Doubled:", arr * 2)
print("Mean:", arr.mean())
print("Values > 25:", arr[arr > 25])

Array: [10 20 30 40]
Type: <class 'numpy.ndarray'>
Shape: (4,)
Doubled: [20 40 60 80]
Mean: 25.0
Values > 25: [30 40]

In [7]:
# Mean with a for loop
numbers = [10, 20, 30, 40]

total = 0
count = 0

for num in numbers:
    total += num
    count += 1

mean_loop = total / count
print("Mean with for loop:", mean_loop)

# Mean with NumPy
numbers_np = np.array([10, 20, 30, 40])
mean_numpy = numbers_np.mean()
print("Mean with NumPy:", mean_numpy)

Mean with for loop: 25.0
Mean with NumPy: 25.0

In [8]:
# Mini TODO
my_arr = np.array([5, 10, 15, 20])

print("Shape:", my_arr.shape)
print("Doubled:", my_arr * 2)
print("Values > 10:", my_arr[my_arr > 10])

Shape: (4,)
Doubled: [10 20 30 40]
Values > 10: [15 20]

---
# IN CLASS — Part 2: Pandas basics

Now we move from arrays to **tables**.
A Pandas **DataFrame** is like a programmable spreadsheet.

In [9]:
# First look at the table
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [10]:
# Shape = rows, columns
print(f"Shape: {df.shape[0]} rows, {df.shape[1]} columns")

Shape: 9800 rows, 17 columns

In [11]:
# Data types and non-null counts
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 1 to 9800
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   str
 1   Order Date     9800 non-null   str
 2   Ship Date      9800 non-null   str
 3   Ship Mode      9800 non-null   str
 4   Customer ID    9800 non-null   str
 5   Customer Name  9800 non-null   str
 6   Segment        9800 non-null   str
 7   Country        9800 non-null   str
 8   City           9800 non-null   str
 9   State          9800 non-null   str
 10  Postal Code    9789 non-null   float64
 11  Region         9800 non-null   str
 12  Product ID     9800 non-null   str
 13  Category       9800 non-null   str
 14  Sub-Category   9800 non-null   str
 15  Product Name   9800 non-null   str
 16  Sales          9800 non-null   float64
dtypes: float64(2), str(15)
memory usage: 1.3 MB

In [12]:
# Summary statistics for numerical columns
df.describe()

        Postal Code         Sales
count   9789.000000   9800.000000
mean   55273.322403    230.769059
std    32041.223413    626.651875
min     1040.000000      0.444000
25%    23223.000000     17.248000
50%    58103.000000     54.490000
75%    90008.000000    210.605000
max    99301.000000  22638.480000

In [13]:
# Quick check for missing values
df.isnull().sum()

Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

### Quick thinking pause
Ask yourself:
- How many rows and columns do we have?
- What are the important columns?
- Which columns are numerical?
- Do we have missing values?

---
# IN CLASS — Part 3: Selecting columns

In [14]:
# One column
df["Sales"].head()

Row ID
1    261.9600
2    731.9400
3     14.6200
4    957.5775
5     22.3680
Name: Sales, dtype: float64

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 1 to 9800
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   str
 1   Order Date     9800 non-null   str
 2   Ship Date      9800 non-null   str
 3   Ship Mode      9800 non-null   str
 4   Customer ID    9800 non-null   str
 5   Customer Name  9800 non-null   str
 6   Segment        9800 non-null   str
 7   Country        9800 non-null   str
 8   City           9800 non-null   str
 9   State          9800 non-null   str
 10  Postal Code    9789 non-null   float64
 11  Region         9800 non-null   str
 12  Product ID     9800 non-null   str
 13  Category       9800 non-null   str
 14  Sub-Category   9800 non-null   str
 15  Product Name   9800 non-null   str
 16  Sales          9800 non-null   float64
dtypes: float64(2), str(15)
memory usage: 1.3 MB

In [18]:
# Multiple columns
df[["City", "Sales"]].head()

                   City     Sales
Row ID
1             Henderson  261.9600
2             Henderson  731.9400
3           Los Angeles   14.6200
4       Fort Lauderdale  957.5775
5       Fort Lauderdale   22.3680

Remember:
- `df["Sales"]` -> one column
- `df[["City", "Sales"]]` -> multiple columns

---
# IN CLASS — Part 4: Filtering rows

In [19]:
# Example 1: one condition
df[df["Region"] == "Central"].head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
15,US-2016-118983,22/11/2016,26/11/2016,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810
16,US-2016-118983,22/11/2016,26/11/2016,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,Texas,76106.0,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544
17,CA-2015-105893,11/11/2015,18/11/2015,Standard Class,PK-19075,Pete Kriz,Consumer,United States,Madison,Wisconsin,53711.0,Central,OFF-ST-10004186,Office Supplies,Storage,"Stur-D-Stor Shelving, Vertical 5-Shelf: 72""H x...",665.880
22,CA-2017-137330,09/12/2017,13/12/2017,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025.0,Central,OFF-AR-10000246,Office Supplies,Art,Newell 318,19.460
23,CA-2017-137330,09/12/2017,13/12/2017,Standard Class,KB-16585,Ken Black,Corporate,United States,Fremont,Nebraska,68025.0,Central,OFF-AP-10001492,Office Supplies,Appliances,"Acco Six-Outlet Power Strip, 4' Cord Length",60.340

In [20]:
# Example 2: one numeric condition
df[df["Sales"] > 1000].head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
11,CA-2015-115812,09/06/2015,14/06/2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,California,90032.0,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.184
25,CA-2016-106320,25/09/2016,30/09/2016,Standard Class,EB-13870,Emily Burns,Consumer,United States,Orem,Utah,84057.0,West,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,1044.630
28,US-2016-150630,17/09/2016,21/09/2016,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,Pennsylvania,19140.0,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.430
36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544
55,CA-2017-105816,11/12/2017,17/12/2017,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,New York,10024.0,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950

In [21]:
# Example 3: combined conditions
df[(df["Sales"] > 1000) & (df["Category"] == "Technology")].head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
36,CA-2017-117590,08/12/2017,10/12/2017,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,Texas,75080.0,Central,TEC-PH-10004977,Technology,Phones,GE 30524EE4,1097.544
55,CA-2017-105816,11/12/2017,17/12/2017,Standard Class,JM-15265,Janet Molinari,Corporate,United States,New York City,New York,10024.0,East,TEC-PH-10002447,Technology,Phones,AT&T CL83451 4-Handset Telephone,1029.950
166,CA-2015-139892,08/09/2015,12/09/2015,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,Texas,78207.0,Central,TEC-MA-10000822,Technology,Machines,Lexmark MX611dhe Monochrome Laser Printer,8159.952
216,CA-2016-146262,02/01/2016,09/01/2016,Standard Class,VW-21775,Victoria Wilson,Corporate,United States,Medina,Ohio,44256.0,East,TEC-MA-10000864,Technology,Machines,Cisco 9971 IP Video Phone Charcoal,1188.000
252,CA-2017-145625,11/09/2017,17/09/2017,Standard Class,KC-16540,Kelly Collister,Consumer,United States,San Diego,California,92037.0,West,TEC-AC-10003832,Technology,Accessories,Logitech P710e Mobile Speakerphone,3347.370

Important:
- Use `&`, not `and`
- Put each condition in parentheses

---
# IN CLASS — Part 5: Grouping and summarizing

In [22]:
# Mean sales by category
df.groupby("Category")["Sales"].mean()

Category
Furniture          350.653790
Office Supplies    119.381001
Technology         456.401474
Name: Sales, dtype: float64

In [23]:
# Total sales by region
df.groupby("Region")["Sales"].sum()

Region
Central    492646.9132
East       669518.7260
South      389151.4590
West       710219.6845
Name: Sales, dtype: float64

In [24]:
# Number of orders by ship mode
df.groupby("Ship Mode")["Order ID"].count()

Ship Mode
First Class       1501
Same Day           538
Second Class      1902
Standard Class    5859
Name: Order ID, dtype: int64

In [25]:
# Quick preview of missing values again
missing = df.isnull().sum()
missing[missing > 0]

Postal Code    11
dtype: int64

## End of in-class core flow

If students understand these ideas, the lesson worked:
1. NumPy = arrays
2. Pandas = tables
3. First data workflow = load -> inspect -> filter -> summarize

> Important: the **original notebook was stronger as a full homework lab**.
> So below we keep the original cleaning / feature engineering backbone almost unchanged.
> For best results after class, rerun the same notebook with the full `SampleSuperstore.csv`.

---
# HOMEWORK / FULL LAB CONTINUES HERE

Below is the **original lab logic** preserved for deeper work:
- handle missing values properly
- remove duplicates
- convert dates
- create customer-level features
- save cleaned outputs

For richer statistics and more realistic outputs, use the **full Superstore dataset** when possible.

---
## Task 2: Missing Values (pre-built)

Check which columns have missing values and how many.

In [26]:
# Count missing values per column
missing = df.isnull().sum()
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)

missing_report = pd.DataFrame({
    'missing_count': missing,
    'missing_pct': missing_pct
})

# Show only columns with missing values
missing_report[missing_report['missing_count'] > 0]

             missing_count  missing_pct
Postal Code             11         0.11

In [27]:
# Fill missing numerical values with median (robust to outliers)
numerical_cols = df.select_dtypes(include=[np.number]).columns
for col in numerical_cols:
    if df[col].isnull().sum() > 0:
        median_val = df[col].median()
        df[col].fillna(median_val, inplace=True)
        print(f"Filled {col} missing values with median: {median_val}")

# Fill missing categorical values with mode
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        mode_val = df[col].mode()[0]
        df[col].fillna(mode_val, inplace=True)
        print(f"Filled {col} missing values with mode: {mode_val}")

# Verify: no more missing values
print(f"\nTotal missing values remaining: {df.isnull().sum().sum()}")

Filled Postal Code missing values with median: 58103.0

Total missing values remaining: 11

C:\Users\user\AppData\Local\Temp\ipykernel_25096\1003425343.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df[col].fillna(median_val, inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_25096\1003425343.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object']).columns

---
## Task 3: Remove Duplicates (pre-built)

In [28]:
# Check for duplicates
n_duplicates = df.duplicated().sum()
print(f"Duplicate rows found: {n_duplicates}")

# Remove duplicates
if n_duplicates > 0:
    df = df.drop_duplicates()
    print(f"After removal: {df.shape[0]} rows remain")
else:
    print("No duplicates to remove.")

Duplicate rows found: 1
After removal: 9799 rows remain

---
## Task 4: Convert Date Columns (TODO)

The `Order Date` and `Ship Date` columns are stored as strings. Convert them to proper datetime objects.

Hint: Use `pd.to_datetime()`. After conversion, verify with `.dtypes`.

In [29]:
# Check current types of date columns
print("Before conversion:")
for col in df.columns:
    if 'date' in col.lower() or 'Date' in col:
        print(f"  {col}: {df[col].dtype}")
        print(f"  Sample value: {df[col].iloc[0]}")

Before conversion:
  Order Date: str
  Sample value: 08/11/2017
  Ship Date: str
  Sample value: 11/11/2017

In [30]:
# TODO: Convert date columns to datetime
# Look at the column names printed above and convert them.
# The column names may vary depending on the dataset version.
#
# Example pattern:
# df['Column Name'] = pd.to_datetime(df['Column Name'])

# Your code here:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d/%m/%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d/%m/%Y")

In [34]:
# TODO: Verify the conversion worked
# Print dtypes for the date columns to confirm they are datetime64

# Your code here:
print(df['Order Date'].dtype)
print(df['Ship Date'].dtype)

datetime64[us]
datetime64[us]

---
## Task 5: Derived Features (TODO)

Create customer-level summary features. These are the building blocks for customer segmentation (Activity 4).

You need to create:
- **total_spending**: Total sales per customer
- **order_frequency**: Number of orders per customer
- **avg_order_value**: Average sales amount per order per customer

Hint: Use `df.groupby('Customer ID')` (or whatever the customer ID column is named).

In [35]:
# First, identify the right column names
print("All columns:")
for col in df.columns:
    print(f"  {col}")

All columns:
  Order ID
  Order Date
  Ship Date
  Ship Mode
  Customer ID
  Customer Name
  Segment
  Country
  City
  State
  Postal Code
  Region
  Product ID
  Category
  Sub-Category
  Product Name
  Sales

In [37]:
# TODO: Create total_spending per customer
# Hint: df.groupby('Customer ID')['Sales'].sum()
#
# Replace column names below with the actual names from your dataset.

# customer_spending = df.groupby('???')['???'].sum()
# customer_spending.name = 'total_spending'

# Your code here:
customer_spending = df.groupby('Customer Name')['Sales'].sum()
customer_spending.name = 'total_spending'
customer_spending

Customer Name
Aaron Bergman          886.156
Aaron Hawkins         1744.700
Aaron Smayling        3050.692
Adam Bellavance       7755.620
Adam Hart             3250.337
                        ...
Xylona Preis          2374.658
Yana Sorensen         6720.444
Yoseph Carroll        5454.350
Zuschuss Carroll      8025.707
Zuschuss Donatelli    1493.944
Name: total_spending, Length: 793, dtype: float64

In [43]:
# TODO: Create order_frequency per customer
# Hint: Count the number of rows (orders) per customer.
# Use .groupby(...).size() or .groupby(...)['some_col'].count()

# Your code here:
order_freq = df.groupby('Customer Name').size()
order_freq.name = 'order_frequency'
order_freq

Customer Name
Aaron Bergman          6
Aaron Hawkins         11
Aaron Smayling        10
Adam Bellavance       18
Adam Hart             20
                      ..
Xylona Preis          28
Yana Sorensen         12
Yoseph Carroll         8
Zuschuss Carroll      31
Zuschuss Donatelli     9
Name: order_frequency, Length: 793, dtype: int64

In [46]:
# TODO: Create avg_order_value per customer
# Hint: Use .groupby(...)['Sales'].mean()

# Your code here:
avg_order_value = df.groupby('Customer Name')['Sales'].mean()
avg_order_value.name = 'avg_order_value'
avg_order_value

Customer Name
Aaron Bergman         147.692667
Aaron Hawkins         158.609091
Aaron Smayling        305.069200
Adam Bellavance       430.867778
Adam Hart             162.516850
                         ...
Xylona Preis           84.809214
Yana Sorensen         560.037000
Yoseph Carroll        681.793750
Zuschuss Carroll      258.893774
Zuschuss Donatelli    165.993778
Name: avg_order_value, Length: 793, dtype: float64

In [47]:
# TODO: Combine all three into a single customer-level DataFrame
# Hint: Use pd.concat([series1, series2, series3], axis=1)
# or create them all at once with .groupby(...).agg(...)

# customer_summary = pd.concat([customer_spending, order_freq, avg_order], axis=1)
# customer_summary.columns = ['total_spending', 'order_frequency', 'avg_order_value']

# Your code here:
customer_summary = pd.concat([customer_spending, order_freq, avg_order_value], axis=1)
customer_summary.columns = ['total_spending', 'order_frequency', 'avg_order_value']
customer_summary

                    total_spending  order_frequency  avg_order_value
Customer Name
Aaron Bergman              886.156                6       147.692667
Aaron Hawkins             1744.700               11       158.609091
Aaron Smayling            3050.692               10       305.069200
Adam Bellavance           7755.620               18       430.867778
Adam Hart                 3250.337               20       162.516850
...                            ...              ...              ...
Xylona Preis              2374.658               28        84.809214
Yana Sorensen             6720.444               12       560.037000
Yoseph Carroll            5454.350                8       681.793750
Zuschuss Carroll          8025.707               31       258.893774
Zuschuss Donatelli        1493.944                9       165.993778

[793 rows x 3 columns]

In [48]:
# TODO: Display the first 10 rows of your customer summary and .describe()

# Your code here:
print(customer_summary.head(10))
print(customer_summary.describe())

                    total_spending  order_frequency  avg_order_value
Customer Name
Aaron Bergman              886.156                6       147.692667
Aaron Hawkins             1744.700               11       158.609091
Aaron Smayling            3050.692               10       305.069200
Adam Bellavance           7755.620               18       430.867778
Adam Hart                 3250.337               20       162.516850
Adam Shillingsburg        3255.310               25       130.212400
Adrian Barton            14473.571               20       723.678550
Adrian Hane               1735.514               16       108.469625
Adrian Shami                58.820                3        19.606667
Aimee Bixby                966.710               12        80.559167
       total_spending  order_frequency  avg_order_value
count      793.000000       793.000000       793.000000
mean      2851.520064        12.356873       227.402594
std       2620.398490         6.160317       190.424661
min          4.833000         1.000000         2.416500
25%       1081.466000         8.000000       115.907000
50%       2215.002000        11.000000       184.048000
75%       3670.258000        16.000000       282.607500
max      25043.050000        35.000000      1751.292000

---
## Task 6: Save Cleaned Data (TODO)

Save the cleaned DataFrame to a new CSV file. Never overwrite the original.

In [49]:
# TODO: Save the cleaned main DataFrame
df.to_csv('superstore_cleaned.csv', index=False)

# TODO: Save the customer summary DataFrame
customer_summary.to_csv('customer_summary.csv')

# Your code here:

---
## Reflection

Answer these in a text cell or comments:

1. Why did we use median instead of mean for filling numerical missing values?
2. What is the difference between the row-level DataFrame (one row per order) and the customer-level summary? When would you use each?
3. If two rows have identical values in every column, are they always true duplicates? When might they not be?

1. Median is less affected by extreme values
2. Row-level: One row = one order. Use for analyzing individual transactions, order patterns, daily operations.
Customer-level: One row = one customer (aggregated data). Use for analyzing customer behavior, customer segmentation, total customer value.
3. Same customer placing the exact same order twice (legitimate)
Different customers with same order details
System recording errors