### Task 1

In [16]:
import pandas as pd

In [15]:
import sys
print(sys.executable)

c:\Users\user\AppData\Local\Programs\Python\Python314\python.exe

In [20]:
df = pd.read_csv("train.csv", index_col = 0)
df.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Row ID,,,,,,,,,,,,,,,,,
1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

### Task 2

In [22]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(9800, 17)
<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 1 to 9800
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   str
 1   Order Date     9800 non-null   str
 2   Ship Date      9800 non-null   str
 3   Ship Mode      9800 non-null   str
 4   Customer ID    9800 non-null   str
 5   Customer Name  9800 non-null   str
 6   Segment        9800 non-null   str
 7   Country        9800 non-null   str
 8   City           9800 non-null   str
 9   State          9800 non-null   str
 10  Postal Code    9789 non-null   float64
 11  Region         9800 non-null   str
 12  Product ID     9800 non-null   str
 13  Category       9800 non-null   str
 14  Sub-Category   9800 non-null   str
 15  Product Name   9800 non-null   str
 16  Sales          9800 non-null   float64
dtypes: float64(2), str(15)
memory usage: 1.3 MB
None
        Postal Code         Sales
count   9789.000000   9800.000000
mean   55273.322403    230.769059
std    32041.223413    626.651875
min     1040.000000      0.444000
25%    23223.000000     17.248000
50%    58103.000000     54.490000
75%    90008.000000    210.605000
max    99301.000000  22638.480000
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

### Task 3

In [31]:
df["Postal Code"] = df["Postal Code"].fillna(df["Postal Code"].mean())
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 1 to 9800
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   str
 1   Order Date     9800 non-null   str
 2   Ship Date      9800 non-null   str
 3   Ship Mode      9800 non-null   str
 4   Customer ID    9800 non-null   str
 5   Customer Name  9800 non-null   str
 6   Segment        9800 non-null   str
 7   Country        9800 non-null   str
 8   City           9800 non-null   str
 9   State          9800 non-null   str
 10  Postal Code    9800 non-null   float64
 11  Region         9800 non-null   str
 12  Product ID     9800 non-null   str
 13  Category       9800 non-null   str
 14  Sub-Category   9800 non-null   str
 15  Product Name   9800 non-null   str
 16  Sales          9800 non-null   float64
dtypes: float64(2), str(15)
memory usage: 1.3 MB

### Task 4

In [38]:
df.duplicated().sum()

np.int64(1)

In [39]:
df.drop_duplicates(inplace = True)

In [40]:
df.duplicated().sum()

np.int64(0)

### Task 5

In [41]:
df.info()

<class 'pandas.DataFrame'>
Index: 9799 entries, 1 to 9800
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9799 non-null   str
 1   Order Date     9799 non-null   str
 2   Ship Date      9799 non-null   str
 3   Ship Mode      9799 non-null   str
 4   Customer ID    9799 non-null   str
 5   Customer Name  9799 non-null   str
 6   Segment        9799 non-null   str
 7   Country        9799 non-null   str
 8   City           9799 non-null   str
 9   State          9799 non-null   str
 10  Postal Code    9799 non-null   float64
 11  Region         9799 non-null   str
 12  Product ID     9799 non-null   str
 13  Category       9799 non-null   str
 14  Sub-Category   9799 non-null   str
 15  Product Name   9799 non-null   str
 16  Sales          9799 non-null   float64
dtypes: float64(2), str(15)
memory usage: 1.3 MB

In [46]:
df["Order Date"] = pd.to_datetime(df["Order Date"], format="%d/%m/%Y")
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="%d/%m/%Y")

In [47]:
df.info()

<class 'pandas.DataFrame'>
Index: 9799 entries, 1 to 9800
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9799 non-null   str
 1   Order Date     9799 non-null   datetime64[us]
 2   Ship Date      9799 non-null   datetime64[us]
 3   Ship Mode      9799 non-null   str
 4   Customer ID    9799 non-null   str
 5   Customer Name  9799 non-null   str
 6   Segment        9799 non-null   str
 7   Country        9799 non-null   str
 8   City           9799 non-null   str
 9   State          9799 non-null   str
 10  Postal Code    9799 non-null   float64
 11  Region         9799 non-null   str
 12  Product ID     9799 non-null   str
 13  Category       9799 non-null   str
 14  Sub-Category   9799 non-null   str
 15  Product Name   9799 non-null   str
 16  Sales          9799 non-null   float64
dtypes: datetime64[us](2), float64(2), str(13)
memory usage: 1.3 MB

### Task 6

In [49]:
df.groupby("Customer Name")["Sales"].sum()

Customer Name
Aaron Bergman          886.156
Aaron Hawkins         1744.700
Aaron Smayling        3050.692
Adam Bellavance       7755.620
Adam Hart             3250.337
                        ...
Xylona Preis          2374.658
Yana Sorensen         6720.444
Yoseph Carroll        5454.350
Zuschuss Carroll      8025.707
Zuschuss Donatelli    1493.944
Name: Sales, Length: 793, dtype: float64

In [56]:
df.groupby("Customer Name")["Order ID"].nunique()

Customer Name
Aaron Bergman          3
Aaron Hawkins          7
Aaron Smayling         7
Adam Bellavance        8
Adam Hart             10
                      ..
Xylona Preis          11
Yana Sorensen          8
Yoseph Carroll         5
Zuschuss Carroll      13
Zuschuss Donatelli     5
Name: Order ID, Length: 793, dtype: int64

In [57]:
df.groupby("Customer Name")["Sales"].mean()

Customer Name
Aaron Bergman         147.692667
Aaron Hawkins         158.609091
Aaron Smayling        305.069200
Adam Bellavance       430.867778
Adam Hart             162.516850
                         ...
Xylona Preis           84.809214
Yana Sorensen         560.037000
Yoseph Carroll        681.793750
Zuschuss Carroll      258.893774
Zuschuss Donatelli    165.993778
Name: Sales, Length: 793, dtype: float64

In [59]:
df.groupby("Customer Name").agg({
    "Sales": ["sum", "mean"],
    "Order ID": "nunique"
})

                       Sales             Order ID
                         sum        mean  nunique
Customer Name
Aaron Bergman        886.156  147.692667        3
Aaron Hawkins       1744.700  158.609091        7
Aaron Smayling      3050.692  305.069200        7
Adam Bellavance     7755.620  430.867778        8
Adam Hart           3250.337  162.516850       10
...                      ...         ...      ...
Xylona Preis        2374.658   84.809214       11
Yana Sorensen       6720.444  560.037000        8
Yoseph Carroll      5454.350  681.793750        5
Zuschuss Carroll    8025.707  258.893774       13
Zuschuss Donatelli  1493.944  165.993778        5

[793 rows x 3 columns]